"""Postmortem generation with per-section evidence citations."""

from __future__ import annotations

from typing import Any

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from sentinel.core.timeutil import iso, utcnow
from sentinel.db.models import Hypothesis, Incident, Postmortem, RemediationAction
from sentinel.llm import get_provider
from sentinel.llm.prompts import SYSTEM_POSTMORTEM, postmortem_prompt
from sentinel.llm.schemas import PostmortemOutput
from sentinel.reporting.why import load_evidence
from sentinel.services.incidents import timeline


async def generate(session: AsyncSession, incident: Incident, *, actor: str = "system") -> Postmortem:
    evidence = await load_evidence(session, incident.id)
    hyps = (await session.execute(select(Hypothesis).where(Hypothesis.incident_id == incident.id).order_by(Hypothesis.rank))).scalars().all()
    top = hyps[0] if hyps else None
    actions = (await session.execute(select(RemediationAction).where(RemediationAction.incident_id == incident.id))).scalars().all()
    events = await timeline(session, incident.id)
    detect_gap = None
    if incident.started_at and incident.detected_at:
        detect_gap = (incident.detected_at - incident.started_at).total_seconds()
    contributing = [h.title for h in hyps[1:3] if h.confidence >= 0.3]
    preventive = []
    if top:
        preventive = [a.title for a in actions if a.kind in ("alert", "config", "manual")]
    ctx = {
        "incident": {
            "key": incident.key,
            "title": incident.title,
            "severity": incident.severity,
            "status": incident.status,
            "primary_service": incident.primary_service,
            "affected_services": list(incident.affected_services or []),
            "started_at": iso(incident.started_at),
            "detected_at": iso(incident.detected_at),
            "resolved_at": iso(incident.resolved_at),
            "resolution_notes": incident.resolution_notes,
        },
        "root_cause": {
            "title": top.title if top else "Undetermined",
            "category": top.category if top else None,
            "confidence": top.confidence if top else 0.0,
            "reasoning": top.reasoning if top else "",
            "supporting": list(top.supporting_evidence or []) if top else [],
            "contradicting": list(top.contradicting_evidence or []) if top else [],
        },
        "timeline": [{"ts": iso(e.ts), "message": e.message, "kind": e.kind} for e in events],
        "remediation": [{"title": a.title, "status": a.status, "kind": a.kind} for a in actions],
        "evidence": evidence,
        "contributing": contributing,
        "preventive": preventive,
        "detection_gap": (f"Onset-to-detection gap: {detect_gap / 60:.1f} minutes." if detect_gap is not None else None),
    }
    provider = get_provider()
    out, res = await provider.structured(SYSTEM_POSTMORTEM, postmortem_prompt(ctx), PostmortemOutput, max_tokens=3000)
    valid = {e["ref"] for e in evidence}
    sections: list[dict[str, Any]] = []
    all_cites: list[str] = []
    for s in out.sections:
        cites = [c for c in s.citations if c in valid]
        all_cites.extend(cites)
        sections.append({"title": s.title, "body": s.body, "citations": cites})
    md = render_markdown(incident, sections, evidence, res.provider, res.model)
    version = 1 + len((await session.execute(select(Postmortem.id).where(Postmortem.incident_id == incident.id))).all())
    pm = Postmortem(incident_id=incident.id, version=version, sections={"sections": sections}, content_md=md, citations=sorted(set(all_cites), key=lambda r: int(r[1:]) if r[1:].isdigit() else 0), generated_by=f"{res.provider}:{res.model}", generated_at=utcnow())
    session.add(pm)
    return pm


def render_markdown(incident: Incident, sections: list[dict[str, Any]], evidence: list[dict[str, Any]], provider: str, model: str) -> str:
    lines = [f"# Postmortem — {incident.key}: {incident.title}", "", f"*Severity {incident.severity} · primary service `{incident.primary_service}` · generated by Sentinel ({provider}/{model})*", ""]
    for s in sections:
        lines.append(f"## {s['title']}")
        lines.append("")
        lines.append(s["body"])
        if s["citations"]:
            lines.append("")
            lines.append("Evidence: " + ", ".join(f"[{c}]" for c in s["citations"]))
        lines.append("")
    lines.append("## Evidence Appendix")
    lines.append("")
    for e in evidence:
        lines.append(f"- **[{e['ref']}]** ({e['kind']}, {e['direction']}, weight {e['weight']:.2f}) {e['summary']}")
    return "\n".join(lines)
