"""initial schema

Revision ID: 121274790340
Revises: 
Create Date: 2026-08-30 00:35:40.660801
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

import sentinel.db.base


revision = '121274790340'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('prefix', sa.String(length=12), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=True),
    sa.Column('created_at', sentinel.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sentinel.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_key_hash'), ['key_hash'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('ts', sentinel.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=True),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_ts', ['ts'], unique=False)

    op.create_table('evaluation_runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('started_at', sentinel.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sentinel.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('service', sa.String(length=128), nullable=False),
    sa.Column('service_version', sa.String(length=64), nullable=True),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('template_hash', sa.String(length=32), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('span_id', sa.String(length=32), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('ts', sentinel.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('log_records', schema=None) as batch_op:
        batch_op.create_index('ix_log_lookup', ['project_id', 'service', 'ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_log_records_template_hash'), ['template_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_log_records_trace_id'), ['trace_id'], unique=False)

    op.create_table('metric_points',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('service', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('labels', sa.JSON(), nullable=False),
    sa.Column('ts', sentinel.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('metric_points', schema=None) as batch_op:
        batch_op.create_index('ix_metric_lookup', ['project_id', 'service', 'name', 'ts'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('environment', sa.String(length=32), nullable=False),
    sa.Column('created_at', sentinel.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_slug'), ['slug'], unique=True)

    op.create_table('spans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('span_id', sa.String(length=32), nullable=False),
    sa.Column('parent_span_id', sa.String(length=32), nullable=True),
    sa.Column('service', sa.String(length=128), nullable=False),
    sa.Column('operation', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('start_ts', sentinel.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('spans', schema=None) as batch_op:
        batch_op.create_index('ix_span_lookup', ['project_id', 'service', 'start_ts'], unique=False)
        batch_op.create_index('ix_span_trace', ['trace_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sentinel.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('deployments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('service', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('previous_version', sa.String(length=64), nullable=True),
    sa.Column('commit_sha', sa.String(length=64), nullable=True),
    sa.Column('commit_message', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=128), nullable=False),
    sa.Column('changed_files', sa.JSON(), nullable=False),
    sa.Column('diff_summary', sa.Text(), nullable=False),
    sa.Column('config_changes', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('deployed_at', sentinel.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('created_at', sentinel.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deployments', schema=None) as batch_op:
        batch_op.create_index('ix_deploy_proj_svc_ts', ['project_id', 'service', 'deployed_at'], unique=False)

    op.create_table('detection_rules',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('metric', sa.String(length=128), nullable=False),
    sa.Column('service', sa.String(length=128), nullable=True),
    sa.Column('aggregation', sa.String(length=16), nullable=False),
    sa.Column('comparator', sa.String(length=4), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('window_s', sa.Integer(), nullable=False),
    sa.Column('for_s', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sentinel.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_rule_name')
    )
    with op.batch_alter_table('detection_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_detection_rules_project_id'), ['project_id'], unique=False)

    op.create_table('evaluation_cases',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('scenario', sa.String(length=128), nullable=False),
    sa.Column('fault_type', sa.String(length=64), nullable=False),
    sa.Column('target_service', sa.String(length=128), nullable=False),
    sa.Column('expected', sa.String(length=64), nullable=False),
    sa.Column('predicted', sa.String(length=64), nullable=True),
    sa.Column('top3', sa.JSON(), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('top3_correct', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_precision', sa.Float(), nullable=False),
    sa.Column('citation_validity', sa.Float(), nullable=False),
    sa.Column('detected', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('llm_ms', sa.Float(), nullable=False),
    sa.Column('incident_id', sa.String(length=32), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['evaluation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluation_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_cases_run_id'), ['run_id'], unique=False)

    op.create_table('fault_experiments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('target_service', sa.String(length=128), nullable=False),
    sa.Column('fault_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('duration_s', sa.Integer(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('expected_root_cause', sa.String(length=64), nullable=True),
    sa.Column('linked_incident_id', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('started_at', sentinel.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sentinel.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', sentinel.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incidents',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('primary_service', sa.String(length=128), nullable=False),
    sa.Column('affected_services', sa.JSON(), nullable=False),
    sa.Column('trigger', sa.JSON(), nullable=False),
    sa.Column('started_at', sentinel.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('detected_at', sentinel.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sentinel.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('root_cause_category', sa.String(length=64), nullable=True),
    sa.Column('root_cause_summary', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('signature', sa.Text(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=False),
    sa.Column('labels', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sentinel.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sentinel.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index('ix_incident_proj_status', ['project_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_key'), ['key'], unique=True)

    op.create_table('service_dependencies',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('target', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('critical', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'source', 'target', name='uq_dep_edge')
    )
    with op.batch_alter_table('service_dependencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_dependencies_project_id'), ['project_id'], unique=False)

    op.create_table('services',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('owner', sa.String(length=128), nullable=False),
    sa.Column('current_version', sa.String(length=64), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sentinel.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_service_project_name')
    )
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_services_project_id'), ['project_id'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('incident_id', sa.String(length=32), nullable=True),
    sa.Column('rule_name', sa.String(length=128), nullable=False),
    sa.Column('service', sa.String(length=128), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('labels', sa.JSON(), nullable=False),
    sa.Column('annotations', sa.JSON(), nullable=False),
    sa.Column('fired_at', sentinel.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sentinel.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index('ix_alert_fp', ['project_id', 'fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_incident_id'), ['incident_id'], unique=False)

    op.create_table('error_clusters',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('incident_id', sa.String(length=32), nullable=False),
    sa.Column('service', sa.String(length=128), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('template_hash', sa.String(length=32), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('baseline_count', sa.Integer(), nullable=False),
    sa.Column('burst_ratio', sa.Float(), nullable=False),
    sa.Column('sample', sa.Text(), nullable=False),
    sa.Column('first_ts', sentinel.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_ts', sentinel.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('error_clusters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_error_clusters_incident_id'), ['incident_id'], unique=False)

    op.create_table('graph_edges',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('incident_id', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=160), nullable=False),
    sa.Column('target', sa.String(length=160), nullable=False),
    sa.Column('relation', sa.String(length=48), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('graph_edges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_graph_edges_incident_id'), ['incident_id'], unique=False)

    op.create_table('graph_nodes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('incident_id', sa.String(length=32), nullable=False),
    sa.Column('key', sa.String(length=160), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id', 'key', name='uq_graph_node')
    )
    with op.batch_alter_table('graph_nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_graph_nodes_incident_id'), ['incident_id'], unique=False)

    op.create_table('incident_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('incident_id', sa.String(length=32), nullable=False),
    sa.Column('ts', sentinel.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incident_events', schema=None) as batch_op:
        batch_op.create_index('ix_event_incident_ts', ['incident_id', 'ts'], unique=False)

    op.create_table('investigations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('incident_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.String(length=32), nullable=False),
    sa.Column('llm_provider', sa.String(length=32), nullable=False),
    sa.Column('llm_model', sa.String(length=64), nullable=True),
    sa.Column('checkpoint', sa.JSON(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('queued_at', sentinel.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('started_at', sentinel.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sentinel.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('llm_ms', sa.Float(), nullable=False),
    sa.Column('llm_calls', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('investigations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investigations_incident_id'), ['incident_id'], unique=False)

    op.create_table('postmortems',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('incident_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('sections', sa.JSON(), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.Column('citations', sa.JSON(), nullable=False),
    sa.Column('generated_by', sa.String(length=64), nullable=False),
    sa.Column('generated_at', sentinel.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('postmortems', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_postmortems_incident_id'), ['incident_id'], unique=False)

    op.create_table('remediation_actions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('incident_id', sa.String(length=32), nullable=False),
    sa.Column('hypothesis_id', sa.String(length=32), nullable=True),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('target_service', sa.String(length=128), nullable=True),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('risk', sa.String(length=8), nullable=False),
    sa.Column('executable', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('requested_by', sa.String(length=64), nullable=True),
    sa.Column('approved_by', sa.String(length=64), nullable=True),
    sa.Column('approval_note', sa.Text(), nullable=False),
    sa.Column('executed_at', sentinel.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('created_at', sentinel.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sentinel.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('remediation_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_remediation_actions_incident_id'), ['incident_id'], unique=False)

    op.create_table('evidence',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('incident_id', sa.String(length=32), nullable=False),
    sa.Column('investigation_id', sa.String(length=32), nullable=True),
    sa.Column('ref', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('service', sa.String(length=128), nullable=True),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('signals', sa.JSON(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('ts_start', sentinel.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('ts_end', sentinel.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', sentinel.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index('ix_evidence_incident', ['incident_id', 'kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_ref'), ['ref'], unique=False)

    op.create_table('hypotheses',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('incident_id', sa.String(length=32), nullable=False),
    sa.Column('investigation_id', sa.String(length=32), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('culprit_service', sa.String(length=128), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('score_breakdown', sa.JSON(), nullable=False),
    sa.Column('supporting_evidence', sa.JSON(), nullable=False),
    sa.Column('contradicting_evidence', sa.JSON(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('verification', sa.JSON(), nullable=False),
    sa.Column('remediation', sa.JSON(), nullable=False),
    sa.Column('created_at', sentinel.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hypotheses', schema=None) as batch_op:
        batch_op.create_index('ix_hyp_incident_rank', ['incident_id', 'rank'], unique=False)

    op.create_table('investigation_steps',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('investigation_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('started_at', sentinel.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sentinel.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('output', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('investigation_id', 'name', name='uq_step_name')
    )
    with op.batch_alter_table('investigation_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investigation_steps_investigation_id'), ['investigation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investigation_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investigation_steps_investigation_id'))

    op.drop_table('investigation_steps')
    with op.batch_alter_table('hypotheses', schema=None) as batch_op:
        batch_op.drop_index('ix_hyp_incident_rank')

    op.drop_table('hypotheses')
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_ref'))
        batch_op.drop_index('ix_evidence_incident')

    op.drop_table('evidence')
    with op.batch_alter_table('remediation_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_remediation_actions_incident_id'))

    op.drop_table('remediation_actions')
    with op.batch_alter_table('postmortems', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_postmortems_incident_id'))

    op.drop_table('postmortems')
    with op.batch_alter_table('investigations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investigations_incident_id'))

    op.drop_table('investigations')
    with op.batch_alter_table('incident_events', schema=None) as batch_op:
        batch_op.drop_index('ix_event_incident_ts')

    op.drop_table('incident_events')
    with op.batch_alter_table('graph_nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_graph_nodes_incident_id'))

    op.drop_table('graph_nodes')
    with op.batch_alter_table('graph_edges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_graph_edges_incident_id'))

    op.drop_table('graph_edges')
    with op.batch_alter_table('error_clusters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_error_clusters_incident_id'))

    op.drop_table('error_clusters')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_incident_id'))
        batch_op.drop_index('ix_alert_fp')

    op.drop_table('alerts')
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_services_project_id'))

    op.drop_table('services')
    with op.batch_alter_table('service_dependencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_dependencies_project_id'))

    op.drop_table('service_dependencies')
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incidents_key'))
        batch_op.drop_index('ix_incident_proj_status')

    op.drop_table('incidents')
    op.drop_table('fault_experiments')
    with op.batch_alter_table('evaluation_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_cases_run_id'))

    op.drop_table('evaluation_cases')
    with op.batch_alter_table('detection_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_detection_rules_project_id'))

    op.drop_table('detection_rules')
    with op.batch_alter_table('deployments', schema=None) as batch_op:
        batch_op.drop_index('ix_deploy_proj_svc_ts')

    op.drop_table('deployments')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('spans', schema=None) as batch_op:
        batch_op.drop_index('ix_span_trace')
        batch_op.drop_index('ix_span_lookup')

    op.drop_table('spans')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_slug'))

    op.drop_table('projects')
    with op.batch_alter_table('metric_points', schema=None) as batch_op:
        batch_op.drop_index('ix_metric_lookup')

    op.drop_table('metric_points')
    with op.batch_alter_table('log_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_log_records_trace_id'))
        batch_op.drop_index(batch_op.f('ix_log_records_template_hash'))
        batch_op.drop_index('ix_log_lookup')

    op.drop_table('log_records')
    op.drop_table('evaluation_runs')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_ts')

    op.drop_table('audit_logs')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_key_hash'))

    op.drop_table('api_keys')
    # ### end Alembic commands ###
